kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "containerinfo.fullname" . }}
  labels:
    {{- include "containerinfo.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "containerinfo.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "containerinfo.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
